### ISSUE TITLE
Add a message and description

### ISSUE THREAD

**Issue by anila-a** [anila-a/cdli-tablet-app#1]
- [ ] Add a welcoming message in _Initial Screen_ for first time users
- [ ] Write a detailed description for the purpose of the mobile app in the _About_ section

**Comment by willismonroe** [comment]
# Welcome Message:
Welcome to the CDLI Tablet app. This app provides daily highlights from the entire CDLI collection with detailed descriptions and links for more information.

# Detailed Description:
This app curates highlighted objects from the CDLI collection. Entries are written by experts in the field. New highlights are available each day, and links are included to find more information on the CDLI website. You can share entries via social media if you want to show a particular object to others. Any feedback should be submitted via the menu in the navigation menu on the left.
